### ISSUE TITLE
No Gist being created

### ISSUE THREAD

**Issue by gep13** [RickStrahl/GistIntegration-MarkdownMonster-Addin#3]
Can I see the logs for the Gist Addin somewhere?

I have just gone through the process of creating a Gist (having setup token, etc) and I get this far:

![image](https://cloud.githubusercontent.com/assets/1271146/22107635/df888c08-de46-11e6-8253-aa45db48b1e8.png)

And I hit Paste Code, and I see this:

![image](https://cloud.githubusercontent.com/assets/1271146/22107644/edf40c90-de46-11e6-8b37-b12d34e493fc.png)

in the bottom left hand corner, but nothing is added into the editor, and no Gist is created on my account.

Any ideas?  Thanks!

**Comment by gep13** [comment]
@RickStrahl any thoughts on what might be going on here?  Thanks!

**Comment by RickStrahl** [comment]
Did you get the Git token setup?

https://github.com/RickStrahl/PasteCodeAsGist-MarkdownMonster-Addin#configuration

**Comment by gep13** [comment]
@RickStrahl yip.  I think I am right in saying that it comes up with anonymous in the above screenshot if that isn't configured.

**Comment by gep13** [comment]
@RickStrahl any other thoughts on this one?  Thanks!

**Comment by RickStrahl** [comment]
What are you using for code? Perhaps the code you're trying to send is too short and Github is refusing it?

**Comment by RickStrahl** [comment]
I don't know if this resolved itself, but I'll close this for now. If you have more info feel free to re-open.
