### ISSUE TITLE
Error/warning messages shown in status bar disappear after 7 seconds

### ISSUE THREAD

**Issue by jeremy-jameson** [RickStrahl/GistIntegration-MarkdownMonster-Addin#8]
As originally mentioned in issue #5, there are a few scenarios where error/warning messages are displayed in the status bar (for example, when saving a Gist fails due to no GitHub user token being configured). These messages currently disappear automatically after a short period of time (i.e. 7 seconds).

I recommend removing the `milliSeconds` parameter value when calling `ShowStatus` to display an error or warning. The way the app currently behaves, it is possible for users to completely miss these errors and warnings (perhaps somewhat contrived, but imagine I get distracted by a phone call or teammate immediately after clicking the save button and just happen to miss the message that my Gist was not saved...:angry:).

Note that this is a simple change -- but I didn't include this in my previous pull request to avoid lumping many changes together. (Trying to be a good contributor since we haven't worked together before :smirk:)

Also, I have ideas for a number of other usability improvements for the Gist integration. such as disabling the save button when there is no GitHub token configured (including showing an error in the status bar). Let me know if you would like me to create additional issues for these (along with corresponding pull requests).

**Comment by RickStrahl** [comment]
Sorry but that's not going to change. I get that errors might be missed, but it's infinitely worse to look at an error message from a few minutes ago after you've moved on to doing something completely differently.

Minor errors are displayed like this throughout Markdown Monster so this would be a global change.  If anything bumping up the timeout to a longer span is something I'd consider but even that I think is not really necessary. if you miss the error at the point of failure, you are definitely not going to notice a long time after...

Thanks for you thoughts though - appreciated!
